name: Android CI/CD

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Build type'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17]
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Grant execute permission
      run: chmod +x gradlew
      
    - name: Build APK
      run: ./gradlew assemble${{ github.event.inputs.build-type || 'Debug' }}
      
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-${{ github.event.inputs.build-type || 'debug' }}-jdk${{ matrix.java }}
        path: app/build/outputs/apk/${{ github.event.inputs.build-type || 'debug' }}/*.apk
        retention-days: 7